r"""
Workforce Astra -- one-shot data pipeline for the CoCo CLI data-gen skill.

Does three things, in order:
  1. Regenerates the 3 CSVs (data/generate_synthetic_data.py) and runs its invariant checks.
  2. Copies the CSVs to a staging directory with NO SPACES in the path.
     (This workspace lives under "F:\AGENTIC WORLD", and a space breaks the
     file:// URI that PUT expects -- so staging is copied to the temp dir first.)
  3. Emits the exact PUT + COPY INTO SQL for CoCo CLI to execute, or runs it
     directly through the `snow` CLI with --run.

Usage:
  python scripts/load_workforce_data.py                # generate + verify + print SQL
  python scripts/load_workforce_data.py --sql-only     # skip generation, just print SQL
  python scripts/load_workforce_data.py --run          # generate + verify + execute via `snow`

Requires: faker (generator), and the Snowflake CLI on PATH for --run.
"""
import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"
GENERATOR = DATA_DIR / "generate_synthetic_data.py"
VOICE_GENERATOR = DATA_DIR / "generate_voice_transcripts.py"
STAGE_NAME = "workforce_astra_csv_stage"

# Load order matters: bands <- workers <- reviews (workers.band_code, reviews.employee_id).
# raw_voice_transcripts is loaded last; its DDL lives in sql/01_create_tables.sql.
#
# THIS LIST IS THE SINGLE CANONICAL DEFINITION OF WHAT GETS LOADED. sql/08_employee_voice.sql
# deliberately contains no PUT/COPY block so there is exactly one load path in the project.
TABLES = [
    ("raw_compensation_bands", "raw_compensation_bands.csv"),
    ("raw_workday_workers", "raw_workday_workers.csv"),
    ("raw_performance_reviews", "raw_performance_reviews.csv"),
    ("raw_voice_transcripts", "raw_voice_transcripts.csv"),
]

# Single source of truth for the CSV file format -- used by both the stage and COPY INTO.
FILE_FORMAT = (
    "TYPE = CSV\n"
    "                 SKIP_HEADER = 1\n"
    "                 FIELD_OPTIONALLY_ENCLOSED_BY = '\"'\n"
    "                 DATE_FORMAT = 'YYYY-MM-DD'\n"
    "                 EMPTY_FIELD_AS_NULL = TRUE\n"
    "                 NULL_IF = ('')"
)


def generate_and_verify():
    print("== Step 1: regenerate synthetic data ==", flush=True)
    subprocess.run([sys.executable, str(GENERATOR)], check=True)
    subprocess.run([sys.executable, str(GENERATOR), "--verify"], check=True)
    if VOICE_GENERATOR.exists():
        subprocess.run([sys.executable, str(VOICE_GENERATOR)], check=True)
        subprocess.run([sys.executable, str(VOICE_GENERATOR), "--verify"], check=True)


def stage_csvs():
    """Copy the CSVs somewhere with no spaces in the path."""
    staging = Path(tempfile.gettempdir()) / "wf_astra_stage"
    if " " in str(staging):
        staging = Path("C:/wf_astra_stage")
    staging.mkdir(parents=True, exist_ok=True)
    for _, filename in TABLES:
        src = DATA_DIR / filename
        if not src.exists():
            sys.exit(f"missing {src} -- run without --sql-only first")
        shutil.copy2(src, staging / filename)
    print(f"\n== Step 3: staged CSVs -> {staging.as_posix()} ==", flush=True)
    return staging


def build_sql(staging: Path) -> str:
    # Windows PUT wants file://C:/path (the POSIX form); Linux wants file:///home/...
    uri_dir = staging.as_posix()
    lines = [
        "-- AUTO-GENERATED by scripts/load_workforce_data.py -- do not hand-edit.",
        "-- Workforce Astra: create objects, stage the CSVs, load the 3 raw tables.",
        "",
        "USE DATABASE WORKFORCE_ASTRA;",
        "USE SCHEMA RAW;",
        "",
        "CREATE OR REPLACE STAGE " + STAGE_NAME,
        "  FILE_FORMAT = (" + FILE_FORMAT + ");",
        "",
    ]
    for _, filename in TABLES:
        lines.append(
            f"PUT file://{uri_dir}/{filename} @{STAGE_NAME} "
            "AUTO_COMPRESS = FALSE OVERWRITE = TRUE;"
        )
    lines.append("")
    for table, filename in TABLES:
        lines += [
            f"-- {table}: TRUNCATE first, then FORCE so a re-run actually reloads",
            f"TRUNCATE TABLE IF EXISTS {table};",
            f"COPY INTO {table}",
            f"  FROM @{STAGE_NAME}/{filename}",
            "  FILE_FORMAT = (" + FILE_FORMAT + ")",
            "  ON_ERROR = ABORT_STATEMENT",
            "  FORCE = TRUE;",
            "",
        ]
    lines += [
        "-- Row counts: must match 5 / 150 / 127 / 18",
        "SELECT 'raw_compensation_bands' AS table_name, COUNT(*) AS row_count FROM raw_compensation_bands",
        "UNION ALL SELECT 'raw_workday_workers',      COUNT(*) FROM raw_workday_workers",
        "UNION ALL SELECT 'raw_performance_reviews',  COUNT(*) FROM raw_performance_reviews",
        "UNION ALL SELECT 'raw_voice_transcripts',    COUNT(*) FROM raw_voice_transcripts;",
        "",
        "-- THE PROOF POINT: these two numbers must differ.",
        "SELECT",
        "  COUNT(*) AS naive_active_headcount,",
        "  COUNT_IF(employment_type = 'FTE') AS governed_active_headcount,",
        "  COUNT(*) - COUNT_IF(employment_type = 'FTE') AS delta",
        "FROM raw_workday_workers",
        "WHERE employee_status = 'Active';",
    ]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sql-only", action="store_true", help="skip generation, just print SQL")
    ap.add_argument("--run", action="store_true", help="execute the SQL with the `snow` CLI")
    args = ap.parse_args()

    if not args.sql_only:
        generate_and_verify()
    staging = stage_csvs()
    sql = build_sql(staging)

    out_file = staging / "load_workforce_astra.sql"
    out_file.write_text(sql, encoding="utf-8")
    print(f"SQL written -> {out_file.as_posix()}\n", flush=True)

    if args.run:
        print("== Step 4: execute via snow CLI ==", flush=True)
        subprocess.run(["snow", "sql", "-f", str(out_file)], check=True)
    else:
        print("== Step 4: SQL for CoCo CLI ==")
        print("Run this with the sql_execute tool (or `snow sql -f "
              f"{out_file.as_posix()}`):\n")
        print(sql)


if __name__ == "__main__":
    main()
